//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV4_60135761.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieuDanhGia
    {
        public int Diem { get; set; }
        public string MaPhieu { get; set; }
        public int MaTieuChi { get; set; }
    
        public virtual PhieuDanhGia PhieuDanhGia { get; set; }
        public virtual TieuChiYeuCau TieuChiYeuCau { get; set; }
    }
}
