//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV4_60135761.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LuongNhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LuongNhanVien()
        {
            this.HopDongs = new HashSet<HopDong>();
        }
    
        public string MaLuong { get; set; }
        [Required(ErrorMessage = "Nhập mức lương.")]
        [Range(155, Int32.MaxValue, ErrorMessage = "Mức lương ít nhất là {1} USD hoặc 3,500,000 VND.")]
        [DisplayFormat(DataFormatString = "{0:#,##0}", ApplyFormatInEditMode = false)]
        public int LuongHienTai { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NgayCapNhat { get; set; }
        public string DonViTien { get; set; }
        public string MaNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong> HopDongs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
