//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV4_60135761.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {
        public int MaTK { get; set; }
        [DataType(DataType.EmailAddress, ErrorMessage = "Nhập đúng định dạng email.")]
        [StringLength(30, ErrorMessage = "Email được phép nhập tối đa 30 kí tự.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Nhập mật khẩu nhân viên.")]
        [StringLength(40, ErrorMessage = "Mật khẩu được phép nhập tối đa 40 kí tự.")]
        public string Password { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NgayTao { get; set; }
        public string Quyen { get; set; }
        public bool KichHoat { get; set; }
        public string MaNV { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
