//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV4_60135761.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TieuChiYeuCau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TieuChiYeuCau()
        {
            this.CTPhieuDanhGias = new HashSet<CTPhieuDanhGia>();
        }
    
        public int MaTieuChi { get; set; }
        public string TenTieuChi { get; set; }
        public Nullable<int> MaLDG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuDanhGia> CTPhieuDanhGias { get; set; }
        public virtual LoaiDanhGia LoaiDanhGia { get; set; }
    }
}
